# Generated by Django 4.2.7 on 2024-01-08 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='email'),
        ),
    ]
